name: Build and Test

on:
  push:
    branches: ['**']
    paths:
      - '**'
      - '!.gitignore'
      - '!LICENSE'
      - '!*.md'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-20.04
    steps:
# Not needed since it's a public repo
#      - name: Granting private modules access
#        run: |
#          git config --global url."https://${{ secrets.GO_MODULES_TOKEN }}:x-oauth-basic@github.com/blacs30".insteadOf "https://github.com/blacs30"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ~1.18

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.47.2

      - name: Run vet.
        run: make vet

      - name: Run lint.
        run: make lint

  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
# Not needed since it's a public repo
#     - name: Granting private modules access
#       run: |
#         git config --global url."https://${{ secrets.GO_MODULES_TOKEN }}:x-oauth-basic@github.com/blacs30".insteadOf "https://github.com/blacs30"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ~1.18

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run test.
        run: make test

      - name: Run Unit tests.
        run: make test-coverage

      # Disable for now, failing again
      #- name: Upload Coverage report to CodeCov
      #  uses: codecov/codecov-action@v1
      #  with:
      #    token: ${{secrets.CODECOV_TOKEN}}
      #    file: ./coverage.txt
      #    flags: unittests
      #    fail_ci_if_error: true

  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: [lint, test]
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-13, ubuntu-20.04]
    steps:
# Not needed since it's a public repo    
#      - name: Granting private modules access
#        run: |
#          git config --global url."https://${{ secrets.GO_MODULES_TOKEN }}:x-oauth-basic@github.com/blacs30".insteadOf "https://github.com/blacs30"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ~1.18

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: make build

      - name: Create universal binary
        if: ${{ matrix.os != 'ubuntu-20.04' }}
        run: |
          make universal-binary
